// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: wine_varieties.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WineReviewRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Review string `protobuf:"bytes,1,opt,name=review,proto3" json:"review,omitempty"`
}

func (x *WineReviewRequest) Reset() {
	*x = WineReviewRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wine_varieties_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WineReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WineReviewRequest) ProtoMessage() {}

func (x *WineReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wine_varieties_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WineReviewRequest.ProtoReflect.Descriptor instead.
func (*WineReviewRequest) Descriptor() ([]byte, []int) {
	return file_wine_varieties_proto_rawDescGZIP(), []int{0}
}

func (x *WineReviewRequest) GetReview() string {
	if x != nil {
		return x.Review
	}
	return ""
}

type WineReviewResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Variety string `protobuf:"bytes,1,opt,name=variety,proto3" json:"variety,omitempty"`
}

func (x *WineReviewResponse) Reset() {
	*x = WineReviewResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wine_varieties_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WineReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WineReviewResponse) ProtoMessage() {}

func (x *WineReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wine_varieties_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WineReviewResponse.ProtoReflect.Descriptor instead.
func (*WineReviewResponse) Descriptor() ([]byte, []int) {
	return file_wine_varieties_proto_rawDescGZIP(), []int{1}
}

func (x *WineReviewResponse) GetVariety() string {
	if x != nil {
		return x.Variety
	}
	return ""
}

var File_wine_varieties_proto protoreflect.FileDescriptor

var file_wine_varieties_proto_rawDesc = []byte{
	0x0a, 0x14, 0x77, 0x69, 0x6e, 0x65, 0x5f, 0x76, 0x61, 0x72, 0x69, 0x65, 0x74, 0x69, 0x65, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x2b, 0x0a, 0x11, 0x57, 0x69,
	0x6e, 0x65, 0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x22, 0x2e, 0x0a, 0x12, 0x57, 0x69, 0x6e, 0x65, 0x52,
	0x65, 0x76, 0x69, 0x65, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x76, 0x61, 0x72, 0x69, 0x65, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x76, 0x61, 0x72, 0x69, 0x65, 0x74, 0x79, 0x32, 0x58, 0x0a, 0x15, 0x57, 0x69, 0x6e, 0x65, 0x43,
	0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x3f, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x57, 0x69, 0x6e, 0x65, 0x56, 0x61, 0x72, 0x69, 0x65,
	0x74, 0x79, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x57, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x76, 0x69,
	0x65, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x57,
	0x69, 0x6e, 0x65, 0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2e, 0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_wine_varieties_proto_rawDescOnce sync.Once
	file_wine_varieties_proto_rawDescData = file_wine_varieties_proto_rawDesc
)

func file_wine_varieties_proto_rawDescGZIP() []byte {
	file_wine_varieties_proto_rawDescOnce.Do(func() {
		file_wine_varieties_proto_rawDescData = protoimpl.X.CompressGZIP(file_wine_varieties_proto_rawDescData)
	})
	return file_wine_varieties_proto_rawDescData
}

var file_wine_varieties_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_wine_varieties_proto_goTypes = []interface{}{
	(*WineReviewRequest)(nil),  // 0: pb.WineReviewRequest
	(*WineReviewResponse)(nil), // 1: pb.WineReviewResponse
}
var file_wine_varieties_proto_depIdxs = []int32{
	0, // 0: pb.WineClassifierService.GetWineVariety:input_type -> pb.WineReviewRequest
	1, // 1: pb.WineClassifierService.GetWineVariety:output_type -> pb.WineReviewResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wine_varieties_proto_init() }
func file_wine_varieties_proto_init() {
	if File_wine_varieties_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wine_varieties_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WineReviewRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wine_varieties_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WineReviewResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wine_varieties_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wine_varieties_proto_goTypes,
		DependencyIndexes: file_wine_varieties_proto_depIdxs,
		MessageInfos:      file_wine_varieties_proto_msgTypes,
	}.Build()
	File_wine_varieties_proto = out.File
	file_wine_varieties_proto_rawDesc = nil
	file_wine_varieties_proto_goTypes = nil
	file_wine_varieties_proto_depIdxs = nil
}
